# Generated by Django 6.0.4 on 2026-05-01 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('degree_level', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=255)),
                ('tuition_fee', models.IntegerField()),
                ('intake', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('living_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_degree', models.CharField(max_length=50)),
                ('field_of_interest', models.CharField(max_length=255)),
                ('preferred_countries', models.JSONField(default=list)),
                ('preferred_cities', models.JSONField(default=list)),
                ('budget', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('ielts', models.FloatField()),
                ('intake', models.CharField(max_length=50)),
                ('career_goal', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cgpa', models.FloatField()),
                ('min_ielts', models.FloatField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
    ]
