# Generated by Django 6.0.4 on 2026-05-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='field',
            new_name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='course',
            name='living_cost',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tuition_fee',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='ielts',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='intake',
        ),
        migrations.AddField(
            model_name='course',
            name='admissions_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='application_difficulty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='average_salary_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='career_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='competitiveness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='coop_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='course_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='employability_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='internship_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='placement_year_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='project_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='relevant_industries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seats_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='thesis_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='active_backlogs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='budget_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='duolingo_overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='english_waiver_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gap_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gmat_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grading_scale',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gre_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ielts_listening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ielts_overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ielts_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ielts_speaking',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ielts_writing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='internship_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='low_tuition_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='no_application_fee_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='no_gre_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_intake',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pte_overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='public_university_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='research_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='scholarship_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='toefl_overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_backlogs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='work_experience_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='accommodation_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='accreditation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='application_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='application_fee_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='university',
            name='application_portal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='average_offer_timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='campus_locations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='common_concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='estimated_monthly_living_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='indian_student_presence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='institution_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='international_admissions_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='university',
            name='job_market_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='living_cost_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='university',
            name='national_ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='nearby_industry_hubs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='official_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='part_time_work_friendliness',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='public_transport_quality',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='qs_ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='refund_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='safety_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarship_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='state_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='the_ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='visa_success_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='weather_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.university'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_cities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='target_degree',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AcademicRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cgpa', models.FloatField(blank=True, null=True)),
                ('min_percentage', models.FloatField(blank=True, null=True)),
                ('accepted_grading_scale', models.CharField(blank=True, max_length=100)),
                ('required_qualification', models.CharField(blank=True, max_length=255)),
                ('required_bachelor_background', models.TextField(blank=True)),
                ('accepted_disciplines', models.TextField(blank=True)),
                ('prerequisite_subjects', models.TextField(blank=True)),
                ('backlog_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('active_backlog_allowed', models.BooleanField(default=False)),
                ('gap_year_tolerance', models.PositiveIntegerField(blank=True, null=True)),
                ('work_experience_required', models.BooleanField(default=False)),
                ('min_work_experience_months', models.PositiveIntegerField(blank=True, null=True)),
                ('research_experience_required', models.BooleanField(default=False)),
                ('academic_flexibility_notes', models.TextField(blank=True)),
                ('common_academic_rejection_reasons', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_requirement', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa_flexible', models.BooleanField(default=False)),
                ('english_score_flexible', models.BooleanField(default=False)),
                ('background_flexible', models.BooleanField(default=False)),
                ('backlog_flexible', models.BooleanField(default=False)),
                ('high_risk_profile_notes', models.TextField(blank=True)),
                ('borderline_profile_notes', models.TextField(blank=True)),
                ('strong_profile_notes', models.TextField(blank=True)),
                ('common_rejection_reasons', models.TextField(blank=True)),
                ('consultant_recommendation_notes', models.TextField(blank=True)),
                ('visa_risk_notes', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_rule', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('fee_period', models.CharField(blank=True, max_length=100)),
                ('estimated_total_tuition', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_total_living_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('scholarship_notes', models.TextField(blank=True)),
                ('fee_notes', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_month', models.CharField(max_length=50)),
                ('intake_year', models.PositiveIntegerField(blank=True, null=True)),
                ('application_open_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_required', models.BooleanField(default=False)),
                ('lor_required', models.BooleanField(default=False)),
                ('number_of_lors', models.PositiveIntegerField(blank=True, null=True)),
                ('resume_required', models.BooleanField(default=False)),
                ('portfolio_required', models.BooleanField(default=False)),
                ('gre_required', models.BooleanField(default=False)),
                ('gmat_required', models.BooleanField(default=False)),
                ('passport_required', models.BooleanField(default=True)),
                ('financial_documents_required', models.BooleanField(default=False)),
                ('document_notes', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ielts_overall', models.FloatField(blank=True, null=True)),
                ('ielts_listening', models.FloatField(blank=True, null=True)),
                ('ielts_reading', models.FloatField(blank=True, null=True)),
                ('ielts_writing', models.FloatField(blank=True, null=True)),
                ('ielts_speaking', models.FloatField(blank=True, null=True)),
                ('toefl_overall', models.FloatField(blank=True, null=True)),
                ('pte_overall', models.FloatField(blank=True, null=True)),
                ('duolingo_overall', models.FloatField(blank=True, null=True)),
                ('english_waiver_available', models.BooleanField(default=False)),
                ('waiver_conditions', models.TextField(blank=True)),
                ('english_score_flexibility_notes', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='english_requirement', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField(blank=True)),
                ('ai_response', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortlisted_courses', models.ManyToManyField(blank=True, related_name='recommendation_logs', to='api.course')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_status', models.CharField(blank=True, max_length=100)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('academic_score', models.FloatField(blank=True, null=True)),
                ('budget_score', models.FloatField(blank=True, null=True)),
                ('course_relevance_score', models.FloatField(blank=True, null=True)),
                ('country_score', models.FloatField(blank=True, null=True)),
                ('city_score', models.FloatField(blank=True, null=True)),
                ('intake_score', models.FloatField(blank=True, null=True)),
                ('career_score', models.FloatField(blank=True, null=True)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_items', to='api.course')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_items', to='api.studentprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseRequirement',
        ),
    ]
