# Generated by Django 6.0.4 on 2026-05-01 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_field_course_field_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='field_of_interest',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='target_degree',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_stream',
            field=models.CharField(blank=True, help_text='For school students: Medical, Non-Medical, Commerce, Arts, Humanities, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='counselor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='disliked_subject_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interested_career_paths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_subject_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subjects_studied',
            field=models.JSONField(blank=True, default=list, help_text="Example: ['Maths', 'Physics', 'Computer Science', 'Economics']"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_major',
            field=models.CharField(blank=True, help_text='For undergraduate students: Computer Science, BCom, Mechanical Engineering, etc.', max_length=255),
        ),
    ]
