# Generated by Django 6.0.4 on 2026-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_whatsapplead'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='human_verified',
            field=models.BooleanField(default=False, help_text='Mark when a human has reviewed and confirmed this course is complete and accurate.'),
        ),
        migrations.AddField(
            model_name='course',
            name='human_verified_at',
            field=models.DateTimeField(blank=True, help_text='When this course was last verified.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='human_verified_by',
            field=models.CharField(blank=True, help_text='Name of the person who verified this course.', max_length=150),
        ),
    ]
