# Generated by Django 6.0.4 on 2026-06-17 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_human_verified_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_stream',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subjects_studied',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('verified', 'Verified'), ('expired', 'Expired')], default='active', max_length=20)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('shortlisted_course_ids', models.JSONField(blank=True, default=list)),
                ('shortlisted_university_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_sessions', to='api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SessionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='api.kiosksession')),
            ],
        ),
    ]
