# Generated by Django 6.0.4 on 2026-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_studentprofile_academic_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosksession',
            name='selected_course_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
