# Generated by Django 6.0.4 on 2026-06-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_kiosksession_selected_course_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosksession',
            name='selected_course_ids',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
