# Generated by Django 6.0.4 on 2026-06-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_kiosksession_selected_course_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kiosksession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='kiosksession',
            name='last_visited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kiosksession',
            name='selected_course_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='kiosksession',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='human_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='human_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='human_verified_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='kiosksession',
            name='phone',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
