# Generated by Django 6.0.4 on 2026-07-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_kiosksession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('checklist', 'Student Visa Checklist'), ('lor_template', 'Letter of Recommendation Template'), ('sop_template', 'Statement of Purpose Template'), ('financial_guide', 'Financial Documents Guide'), ('health_guide', 'Health Insurance Guide'), ('admission_letter', 'Admission Letter Template'), ('passport_guide', 'Passport & ID Documents Guide')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.RemoveField(
            model_name='academicrequirement',
            name='academic_flexibility_notes',
        ),
        migrations.RemoveField(
            model_name='academicrequirement',
            name='accepted_disciplines',
        ),
        migrations.RemoveField(
            model_name='academicrequirement',
            name='common_academic_rejection_reasons',
        ),
        migrations.RemoveField(
            model_name='academicrequirement',
            name='prerequisite_subjects',
        ),
        migrations.RemoveField(
            model_name='course',
            name='admissions_notes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='application_difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='average_salary_notes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='career_outcomes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='competitiveness',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coop_available',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='employability_notes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='internship_available',
        ),
        migrations.RemoveField(
            model_name='course',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='course',
            name='placement_year_available',
        ),
        migrations.RemoveField(
            model_name='course',
            name='project_option',
        ),
        migrations.RemoveField(
            model_name='course',
            name='relevant_industries',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats_available',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thesis_option',
        ),
        migrations.RemoveField(
            model_name='coursefee',
            name='fee_notes',
        ),
        migrations.RemoveField(
            model_name='courseintake',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='courseintake',
            name='status',
        ),
        migrations.RemoveField(
            model_name='englishrequirement',
            name='english_score_flexibility_notes',
        ),
        migrations.RemoveField(
            model_name='englishrequirement',
            name='english_waiver_available',
        ),
        migrations.RemoveField(
            model_name='englishrequirement',
            name='waiver_conditions',
        ),
        migrations.CreateModel(
            name='CountryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('australia', 'Australia'), ('canada', 'Canada'), ('uk', 'United Kingdom'), ('germany', 'Germany'), ('latvia', 'Latvia'), ('newzealand', 'New Zealand'), ('cyprus', 'Cyprus')], max_length=50)),
                ('file_path', models.CharField(help_text='e.g., documents/australia/checklist.pdf', max_length=255)),
                ('file_name', models.CharField(help_text='e.g., Australia_Student_Visa_Checklist.pdf', max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('required', models.BooleanField(default=True, help_text='Is this document mandatory?')),
                ('description', models.TextField(blank=True, help_text='Description of what this document contains')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.countrydocumenttype')),
            ],
            options={
                'verbose_name': 'Country Document',
                'verbose_name_plural': 'Country Documents',
                'ordering': ['country', 'document_type'],
                'unique_together': {('country', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('voice', 'Voice Agent'), ('chatbot', 'Chatbot'), ('manual', 'Manual (Admin)')], max_length=20)),
                ('country', models.CharField(choices=[('australia', 'Australia'), ('canada', 'Canada'), ('uk', 'United Kingdom'), ('germany', 'Germany'), ('latvia', 'Latvia'), ('newzealand', 'New Zealand'), ('cyprus', 'Cyprus')], max_length=50)),
                ('conversation_text', models.TextField(help_text='What the agent and student discussed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documents_identified', models.ManyToManyField(blank=True, help_text='Documents identified as needed', to='api.countrydocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_conversations', to='api.studentprofile')),
            ],
            options={
                'verbose_name': 'Document Conversation Log',
                'verbose_name_plural': 'Document Conversation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('australia', 'Australia'), ('canada', 'Canada'), ('uk', 'United Kingdom'), ('germany', 'Germany'), ('latvia', 'Latvia'), ('newzealand', 'New Zealand'), ('cyprus', 'Cyprus')], max_length=50)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('preparing', 'Preparing to Send'), ('sent', 'Sent via WhatsApp'), ('downloaded', 'Downloaded by Student'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='WhatsApp message ID from Meta API', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this request')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='student_requests', to='api.countrydocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='api.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Document Request',
                'verbose_name_plural': 'Student Document Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
