import type { DetailedCourse } from "./types";

const demoCourses: DetailedCourse[] = [
  {
    course_id: 1,
    title: "Master of Business Administration",
    university: {
      name: "RMIT University",
      official_website: "https://www.rmit.edu.au",
      country: "Australia",
      state_province: "Victoria",
      city: "Melbourne",
      campus_locations: "124 La Trobe Street, Melbourne VIC 3000",
      institution_type: "University",
      ownership_type: "Public",
      qs_ranking: "Top 150 globally",
      national_ranking: "Top 15 in Australia",
      ranking_notes: "Indicative demonstration ranking",
      application_fee: 100,
      application_fee_currency: "AUD",
      scholarship_available: true,
      accommodation_available: true,
      estimated_monthly_living_cost: 2400,
      living_cost_currency: "AUD",
    },
    degree_level: "Master's degree",
    field_of_study: "Business and Management",
    specialization: "Leadership and Strategy",
    department: "Graduate School of Business and Law",
    faculty: "College of Business and Law",
    duration_months: 24,
    mode: "Full-time · On-campus",
    campus: "Melbourne City Campus",
    course_url: "https://www.rmit.edu.au",
    course_summary: "Build the strategic, financial and leadership capabilities needed to manage complex organisations. This MBA combines contemporary business theory with applied projects, collaborative workshops and industry-informed learning in the heart of Melbourne.",
    modules: "The program covers strategic management, business analytics, corporate finance, marketing, responsible leadership and a final industry capstone project.",
    credits: "192 credit points",
    thesis_option: false,
    project_option: true,
    internship_available: true,
    career_outcomes: "Business consultant, strategy manager, operations director, product leader and entrepreneur.",
    relevant_industries: "Consulting, technology, financial services, retail and professional services",
    application_difficulty: "Competitive",
    tuition_fee: 48000,
    tuition_currency: "AUD",
    fee_period: "per year",
    intake_labels: ["February 2027", "July 2027", "October 2027"],
    ielts_overall: 6.5,
    admissions_notes: "A recognised bachelor degree or equivalent qualification. Applicants with substantial professional experience may be considered through an alternative-entry assessment.",
    gallery_images: ["/student-campus-1.webp", "/student-campus-2.webp", "/birmingham-city-university.webp", "/university-of-manitoba.jpg"],
  },
  {
    course_id: 2,
    title: "Master of Data Science",
    university: {
      name: "University of Manitoba",
      official_website: "https://umanitoba.ca",
      country: "Canada",
      state_province: "Manitoba",
      city: "Winnipeg",
      campus_locations: "66 Chancellors Circle, Winnipeg, Manitoba",
      institution_type: "Research University",
      ownership_type: "Public",
      qs_ranking: "Globally ranked institution",
      national_ranking: "Leading Canadian research university",
      ranking_notes: "Indicative demonstration ranking",
      application_fee: 130,
      application_fee_currency: "CAD",
      scholarship_available: true,
      accommodation_available: true,
      estimated_monthly_living_cost: 1750,
      living_cost_currency: "CAD",
    },
    degree_level: "Master's degree",
    field_of_study: "Data Science",
    specialization: "Applied Machine Learning",
    department: "Department of Computer Science",
    faculty: "Faculty of Science",
    duration_months: 24,
    mode: "Full-time · On-campus",
    campus: "Fort Garry Campus",
    course_url: "https://umanitoba.ca",
    course_summary: "Develop advanced capabilities in statistical modelling, machine learning, data engineering and responsible artificial intelligence. Applied labs and an industry capstone help students turn complex information into practical decisions.",
    modules: "Core study includes data systems, statistical inference, machine learning, visual analytics, cloud computing and a team-based capstone.",
    credits: "30 credit hours",
    thesis_option: true,
    project_option: true,
    internship_available: true,
    career_outcomes: "Data scientist, machine-learning engineer, analytics consultant and data product manager.",
    relevant_industries: "Technology, agriculture, healthcare, finance and public services",
    application_difficulty: "Competitive",
    tuition_fee: 26000,
    tuition_currency: "CAD",
    fee_period: "per year",
    intake_labels: ["January 2027", "May 2027", "September 2027"],
    ielts_overall: 6.5,
    admissions_notes: "A four-year bachelor degree in computing, mathematics, engineering or a related quantitative discipline with appropriate programming preparation.",
    gallery_images: ["/university-of-manitoba.jpg", "/student-campus-2.webp", "/student-campus-1.webp", "/georgian-college-canada.jpg"],
  },
  {
    course_id: 3,
    title: "MSc Cyber Security",
    university: {
      name: "Birmingham City University",
      official_website: "https://www.bcu.ac.uk",
      country: "United Kingdom",
      state_province: "West Midlands",
      city: "Birmingham",
      campus_locations: "Curzon Building, 4 Cardigan Street, Birmingham",
      institution_type: "University",
      ownership_type: "Public",
      qs_ranking: "Internationally recognised",
      national_ranking: "Career-focused UK university",
      ranking_notes: "Indicative demonstration ranking",
      application_fee: null,
      application_fee_currency: "GBP",
      scholarship_available: true,
      accommodation_available: true,
      estimated_monthly_living_cost: 1250,
      living_cost_currency: "GBP",
    },
    degree_level: "Master of Science",
    field_of_study: "Cyber Security",
    specialization: "Digital Forensics and Network Security",
    department: "School of Computing and Digital Technology",
    faculty: "Faculty of Computing, Engineering and the Built Environment",
    duration_months: 12,
    mode: "Full-time · On-campus",
    campus: "City Centre Campus",
    course_url: "https://www.bcu.ac.uk",
    course_summary: "Learn to assess cyber risk, investigate incidents and design resilient systems in practical security labs. The course connects current technical practice with governance, ethics and professional response planning.",
    modules: "Study areas include ethical hacking, network security, digital forensics, cloud security, governance and an individual research project.",
    credits: "180 UK credits",
    thesis_option: true,
    project_option: true,
    internship_available: false,
    career_outcomes: "Security analyst, penetration tester, incident responder, forensic investigator and security consultant.",
    relevant_industries: "Technology, banking, government, consulting and critical infrastructure",
    application_difficulty: "Moderate",
    tuition_fee: 18500,
    tuition_currency: "GBP",
    fee_period: "total course",
    intake_labels: ["January 2027", "September 2027"],
    ielts_overall: 6,
    admissions_notes: "An honours degree in computing, engineering or a closely related subject. Applicants with relevant professional certifications may also be considered.",
    gallery_images: ["/birmingham-city-university.webp", "/student-campus-1.webp", "/student-campus-2.webp", "/humboldt-university-berlin.jpg"],
  },
];

export function getDemoCourse(courseId: number): DetailedCourse {
  const selected = demoCourses.find((course) => course.course_id === courseId)
    ?? demoCourses[Math.abs(courseId || 1) % demoCourses.length];

  return { ...selected, course_id: courseId || selected.course_id };
}
